//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class CityFlow {
  public static string ARGS_END {
    get {
      string ret = CityFlowPINVOKE.ARGS_END_get();
      return ret;
    } 
  }

  public static string remove_character(string str, char c) {
    string ret = CityFlowPINVOKE.remove_character(str, c);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector split_str(string s, string delimiter) {
    StringVector ret = new StringVector(CityFlowPINVOKE.split_str__SWIG_0(s, delimiter), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector split_str(string s) {
    StringVector ret = new StringVector(CityFlowPINVOKE.split_str__SWIG_1(s), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double eps {
    get {
      double ret = CityFlowPINVOKE.eps_get();
      return ret;
    } 
  }

  public static uint JSON_BUFFER_SIZE {
    get {
      uint ret = CityFlowPINVOKE.JSON_BUFFER_SIZE_get();
      return ret;
    } 
  }

  public static double crossMultiply(Point A, Point B) {
    double ret = CityFlowPINVOKE.crossMultiply(Point.getCPtr(A), Point.getCPtr(B));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double dotMultiply(Point A, Point B) {
    double ret = CityFlowPINVOKE.dotMultiply(Point.getCPtr(A), Point.getCPtr(B));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double calcAng(Point A, Point B) {
    double ret = CityFlowPINVOKE.calcAng(Point.getCPtr(A), Point.getCPtr(B));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static Point calcIntersectPoint(Point A, Point B, Point C, Point D) {
    Point ret = new Point(CityFlowPINVOKE.calcIntersectPoint(Point.getCPtr(A), Point.getCPtr(B), Point.getCPtr(C), Point.getCPtr(D)), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool onSegment(Point A, Point B, Point P) {
    bool ret = CityFlowPINVOKE.onSegment(Point.getCPtr(A), Point.getCPtr(B), Point.getCPtr(P));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double max2double(double x, double y) {
    double ret = CityFlowPINVOKE.max2double(x, y);
    return ret;
  }

  public static double min2double(double x, double y) {
    double ret = CityFlowPINVOKE.min2double(x, y);
    return ret;
  }

  public static string double2string(double x) {
    string ret = CityFlowPINVOKE.double2string(x);
    return ret;
  }

  public static IntVector generateRandomIndices(uint n, SWIGTYPE_p_std__mt19937 rnd) {
    IntVector ret = new IntVector(CityFlowPINVOKE.generateRandomIndices(n, SWIGTYPE_p_std__mt19937.getCPtr(rnd)), true);
    return ret;
  }

  public static bool readJsonFromFile(string filename, SWIGTYPE_p_rapidjson__Document document) {
    bool ret = CityFlowPINVOKE.readJsonFromFile(filename, SWIGTYPE_p_rapidjson__Document.getCPtr(document));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool writeJsonToFile(string filename, SWIGTYPE_p_rapidjson__Document document) {
    bool ret = CityFlowPINVOKE.writeJsonToFile(filename, SWIGTYPE_p_rapidjson__Document.getCPtr(document));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_rapidjson__Value getJsonMemberValue(string name, SWIGTYPE_p_rapidjson__Value object_) {
    SWIGTYPE_p_rapidjson__Value ret = new SWIGTYPE_p_rapidjson__Value(CityFlowPINVOKE.getJsonMemberValue(name, SWIGTYPE_p_rapidjson__Value.getCPtr(object_)), false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_rapidjson__Value getJsonMemberObject(string name, SWIGTYPE_p_rapidjson__Value object_) {
    SWIGTYPE_p_rapidjson__Value ret = new SWIGTYPE_p_rapidjson__Value(CityFlowPINVOKE.getJsonMemberObject(name, SWIGTYPE_p_rapidjson__Value.getCPtr(object_)), false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_rapidjson__Value getJsonMemberArray(string name, SWIGTYPE_p_rapidjson__Value object_) {
    SWIGTYPE_p_rapidjson__Value ret = new SWIGTYPE_p_rapidjson__Value(CityFlowPINVOKE.getJsonMemberArray(name, SWIGTYPE_p_rapidjson__Value.getCPtr(object_)), false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
