//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class DrivablePointerVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<Drivable>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DrivablePointerVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DrivablePointerVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DrivablePointerVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DrivablePointerVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_DrivablePointerVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DrivablePointerVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Drivable element in c) {
      this.Add(element);
    }
  }

  public DrivablePointerVector(global::System.Collections.Generic.IEnumerable<Drivable> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Drivable element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Drivable this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Drivable[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Drivable[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Drivable[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Drivable[] ToArray() {
    Drivable[] array = new Drivable[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Drivable> global::System.Collections.Generic.IEnumerable<Drivable>.GetEnumerator() {
    return new DrivablePointerVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new DrivablePointerVectorEnumerator(this);
  }

  public DrivablePointerVectorEnumerator GetEnumerator() {
    return new DrivablePointerVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class DrivablePointerVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Drivable>
  {
    private DrivablePointerVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public DrivablePointerVectorEnumerator(DrivablePointerVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Drivable Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Drivable)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public DrivablePointerVector() : this(CityFlowPINVOKE.new_DrivablePointerVector__SWIG_0(), true) {
  }

  public DrivablePointerVector(DrivablePointerVector other) : this(CityFlowPINVOKE.new_DrivablePointerVector__SWIG_1(DrivablePointerVector.getCPtr(other)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    CityFlowPINVOKE.DrivablePointerVector_Clear(swigCPtr);
  }

  public void Add(Drivable x) {
    CityFlowPINVOKE.DrivablePointerVector_Add(swigCPtr, Drivable.getCPtr(x));
  }

  private uint size() {
    uint ret = CityFlowPINVOKE.DrivablePointerVector_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = CityFlowPINVOKE.DrivablePointerVector_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CityFlowPINVOKE.DrivablePointerVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CityFlowPINVOKE.DrivablePointerVector_reserve(swigCPtr, n);
  }

  public DrivablePointerVector(int capacity) : this(CityFlowPINVOKE.new_DrivablePointerVector__SWIG_2(capacity), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private Drivable getitemcopy(int index) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.DrivablePointerVector_getitemcopy(swigCPtr, index);
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Drivable getitem(int index) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.DrivablePointerVector_getitem(swigCPtr, index);
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Drivable val) {
    CityFlowPINVOKE.DrivablePointerVector_setitem(swigCPtr, index, Drivable.getCPtr(val));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(DrivablePointerVector values) {
    CityFlowPINVOKE.DrivablePointerVector_AddRange(swigCPtr, DrivablePointerVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public DrivablePointerVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.DrivablePointerVector_GetRange(swigCPtr, index, count);
    DrivablePointerVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DrivablePointerVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Drivable x) {
    CityFlowPINVOKE.DrivablePointerVector_Insert(swigCPtr, index, Drivable.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, DrivablePointerVector values) {
    CityFlowPINVOKE.DrivablePointerVector_InsertRange(swigCPtr, index, DrivablePointerVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CityFlowPINVOKE.DrivablePointerVector_RemoveAt(swigCPtr, index);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CityFlowPINVOKE.DrivablePointerVector_RemoveRange(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public static DrivablePointerVector Repeat(Drivable value, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.DrivablePointerVector_Repeat(Drivable.getCPtr(value), count);
    DrivablePointerVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DrivablePointerVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CityFlowPINVOKE.DrivablePointerVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CityFlowPINVOKE.DrivablePointerVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, DrivablePointerVector values) {
    CityFlowPINVOKE.DrivablePointerVector_SetRange(swigCPtr, index, DrivablePointerVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(Drivable value) {
    bool ret = CityFlowPINVOKE.DrivablePointerVector_Contains(swigCPtr, Drivable.getCPtr(value));
    return ret;
  }

  public int IndexOf(Drivable value) {
    int ret = CityFlowPINVOKE.DrivablePointerVector_IndexOf(swigCPtr, Drivable.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(Drivable value) {
    int ret = CityFlowPINVOKE.DrivablePointerVector_LastIndexOf(swigCPtr, Drivable.getCPtr(value));
    return ret;
  }

  public bool Remove(Drivable value) {
    bool ret = CityFlowPINVOKE.DrivablePointerVector_Remove(swigCPtr, Drivable.getCPtr(value));
    return ret;
  }

}

}
