//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Drivable : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Drivable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Drivable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Drivable obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Drivable() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityEnginePINVOKE.delete_Drivable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_std__listT_CityFlow__Vehicle_p_t getVehicles() {
    SWIGTYPE_p_std__listT_CityFlow__Vehicle_p_t ret = new SWIGTYPE_p_std__listT_CityFlow__Vehicle_p_t(CityEnginePINVOKE.Drivable_getVehicles__SWIG_0(swigCPtr), false);
    return ret;
  }

  public double getLength() {
    double ret = CityEnginePINVOKE.Drivable_getLength(swigCPtr);
    return ret;
  }

  public double getWidth() {
    double ret = CityEnginePINVOKE.Drivable_getWidth(swigCPtr);
    return ret;
  }

  public double getMaxSpeed() {
    double ret = CityEnginePINVOKE.Drivable_getMaxSpeed(swigCPtr);
    return ret;
  }

  public uint getVehicleCount() {
    uint ret = CityEnginePINVOKE.Drivable_getVehicleCount(swigCPtr);
    return ret;
  }

  public Drivable.DrivableType getDrivableType() {
    Drivable.DrivableType ret = (Drivable.DrivableType)CityEnginePINVOKE.Drivable_getDrivableType(swigCPtr);
    return ret;
  }

  public bool isLane() {
    bool ret = CityEnginePINVOKE.Drivable_isLane(swigCPtr);
    return ret;
  }

  public bool isLaneLink() {
    bool ret = CityEnginePINVOKE.Drivable_isLaneLink(swigCPtr);
    return ret;
  }

  public Vehicle getFirstVehicle() {
    global::System.IntPtr cPtr = CityEnginePINVOKE.Drivable_getFirstVehicle(swigCPtr);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public Vehicle getLastVehicle() {
    global::System.IntPtr cPtr = CityEnginePINVOKE.Drivable_getLastVehicle(swigCPtr);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_Point getPointByDistance(double dis) {
    SWIGTYPE_p_Point ret = new SWIGTYPE_p_Point(CityEnginePINVOKE.Drivable_getPointByDistance(swigCPtr, dis), true);
    return ret;
  }

  public SWIGTYPE_p_Point getDirectionByDistance(double dis) {
    SWIGTYPE_p_Point ret = new SWIGTYPE_p_Point(CityEnginePINVOKE.Drivable_getDirectionByDistance(swigCPtr, dis), true);
    return ret;
  }

  public void pushVehicle(Vehicle vehicle) {
    CityEnginePINVOKE.Drivable_pushVehicle(swigCPtr, Vehicle.getCPtr(vehicle));
  }

  public void popVehicle() {
    CityEnginePINVOKE.Drivable_popVehicle(swigCPtr);
  }

  public virtual SWIGTYPE_p_std__string getId() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityEnginePINVOKE.Drivable_getId(swigCPtr), true);
    return ret;
  }

  public enum DrivableType {
    LANE = 0,
    LANELINK = 1
  }

}

}
