//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Engine : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Engine(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Engine obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Engine obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Engine() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityEnginePINVOKE.delete_Engine(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_std__mt19937 rnd {
    set {
      CityEnginePINVOKE.Engine_rnd_set(swigCPtr, SWIGTYPE_p_std__mt19937.getCPtr(value));
      if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__mt19937 ret = new SWIGTYPE_p_std__mt19937(CityEnginePINVOKE.Engine_rnd_get(swigCPtr), true);
      if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public Engine(SWIGTYPE_p_std__string configFile, int threadNum) : this(CityEnginePINVOKE.new_Engine(SWIGTYPE_p_std__string.getCPtr(configFile), threadNum), true) {
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public double getInterval() {
    double ret = CityEnginePINVOKE.Engine_getInterval(swigCPtr);
    return ret;
  }

  public bool hasLaneChange() {
    bool ret = CityEnginePINVOKE.Engine_hasLaneChange(swigCPtr);
    return ret;
  }

  public bool loadConfig(SWIGTYPE_p_std__string configFile) {
    bool ret = CityEnginePINVOKE.Engine_loadConfig(swigCPtr, SWIGTYPE_p_std__string.getCPtr(configFile));
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void notifyCross() {
    CityEnginePINVOKE.Engine_notifyCross(swigCPtr);
  }

  public void nextStep() {
    CityEnginePINVOKE.Engine_nextStep(swigCPtr);
  }

  public bool checkPriority(int priority) {
    bool ret = CityEnginePINVOKE.Engine_checkPriority(swigCPtr, priority);
    return ret;
  }

  public void pushVehicle(SWIGTYPE_p_Vehicle vehicle, bool pushToDrivable) {
    CityEnginePINVOKE.Engine_pushVehicle__SWIG_0(swigCPtr, SWIGTYPE_p_Vehicle.getCPtr(vehicle), pushToDrivable);
  }

  public void pushVehicle(SWIGTYPE_p_Vehicle vehicle) {
    CityEnginePINVOKE.Engine_pushVehicle__SWIG_1(swigCPtr, SWIGTYPE_p_Vehicle.getCPtr(vehicle));
  }

  public void setLogFile(SWIGTYPE_p_std__string jsonFile, SWIGTYPE_p_std__string logFile) {
    CityEnginePINVOKE.Engine_setLogFile(swigCPtr, SWIGTYPE_p_std__string.getCPtr(jsonFile), SWIGTYPE_p_std__string.getCPtr(logFile));
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void initSegments() {
    CityEnginePINVOKE.Engine_initSegments(swigCPtr);
  }

  public void pushVehicle(SWIGTYPE_p_std__mapT_std__string_double_t info, SWIGTYPE_p_std__vectorT_std__string_t roads) {
    CityEnginePINVOKE.Engine_pushVehicle__SWIG_2(swigCPtr, SWIGTYPE_p_std__mapT_std__string_double_t.getCPtr(info), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(roads));
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public uint getVehicleCount() {
    uint ret = CityEnginePINVOKE.Engine_getVehicleCount(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getVehicles(bool includeWaiting) {
    SWIGTYPE_p_std__vectorT_std__string_t ret = new SWIGTYPE_p_std__vectorT_std__string_t(CityEnginePINVOKE.Engine_getVehicles__SWIG_0(swigCPtr, includeWaiting), true);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getVehicles() {
    SWIGTYPE_p_std__vectorT_std__string_t ret = new SWIGTYPE_p_std__vectorT_std__string_t(CityEnginePINVOKE.Engine_getVehicles__SWIG_1(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_std__mapT_std__string_int_t getLaneVehicleCount() {
    SWIGTYPE_p_std__mapT_std__string_int_t ret = new SWIGTYPE_p_std__mapT_std__string_int_t(CityEnginePINVOKE.Engine_getLaneVehicleCount(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_std__mapT_std__string_int_t getLaneWaitingVehicleCount() {
    SWIGTYPE_p_std__mapT_std__string_int_t ret = new SWIGTYPE_p_std__mapT_std__string_int_t(CityEnginePINVOKE.Engine_getLaneWaitingVehicleCount(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t getLaneVehicles() {
    SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t ret = new SWIGTYPE_p_std__mapT_std__string_std__vectorT_std__string_t_t(CityEnginePINVOKE.Engine_getLaneVehicles(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_std__mapT_std__string_double_t getVehicleSpeed() {
    SWIGTYPE_p_std__mapT_std__string_double_t ret = new SWIGTYPE_p_std__mapT_std__string_double_t(CityEnginePINVOKE.Engine_getVehicleSpeed(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_std__mapT_std__string_double_t getVehicleDistance() {
    SWIGTYPE_p_std__mapT_std__string_double_t ret = new SWIGTYPE_p_std__mapT_std__string_double_t(CityEnginePINVOKE.Engine_getVehicleDistance(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_std__string getLeader(SWIGTYPE_p_std__string vehicleId) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityEnginePINVOKE.Engine_getLeader(swigCPtr, SWIGTYPE_p_std__string.getCPtr(vehicleId)), true);
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getCurrentTime() {
    double ret = CityEnginePINVOKE.Engine_getCurrentTime(swigCPtr);
    return ret;
  }

  public double getAverageTravelTime() {
    double ret = CityEnginePINVOKE.Engine_getAverageTravelTime(swigCPtr);
    return ret;
  }

  public void setTrafficLightPhase(SWIGTYPE_p_std__string id, int phaseIndex) {
    CityEnginePINVOKE.Engine_setTrafficLightPhase(swigCPtr, SWIGTYPE_p_std__string.getCPtr(id), phaseIndex);
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setReplayLogFile(SWIGTYPE_p_std__string logFile) {
    CityEnginePINVOKE.Engine_setReplayLogFile(swigCPtr, SWIGTYPE_p_std__string.getCPtr(logFile));
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setSaveReplay(bool open) {
    CityEnginePINVOKE.Engine_setSaveReplay(swigCPtr, open);
  }

  public void setVehicleSpeed(SWIGTYPE_p_std__string id, double speed) {
    CityEnginePINVOKE.Engine_setVehicleSpeed(swigCPtr, SWIGTYPE_p_std__string.getCPtr(id), speed);
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setRandomSeed(int seed) {
    CityEnginePINVOKE.Engine_setRandomSeed(swigCPtr, seed);
  }

  public void reset(bool resetRnd) {
    CityEnginePINVOKE.Engine_reset__SWIG_0(swigCPtr, resetRnd);
  }

  public void reset() {
    CityEnginePINVOKE.Engine_reset__SWIG_1(swigCPtr);
  }

  public void load(SWIGTYPE_p_Archive archive) {
    CityEnginePINVOKE.Engine_load(swigCPtr, SWIGTYPE_p_Archive.getCPtr(archive));
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Archive snapshot() {
    SWIGTYPE_p_Archive ret = new SWIGTYPE_p_Archive(CityEnginePINVOKE.Engine_snapshot(swigCPtr), true);
    return ret;
  }

  public void loadFromFile(string fileName) {
    CityEnginePINVOKE.Engine_loadFromFile(swigCPtr, fileName);
  }

  public bool setRoute(SWIGTYPE_p_std__string vehicle_id, SWIGTYPE_p_std__vectorT_std__string_t anchor_id) {
    bool ret = CityEnginePINVOKE.Engine_setRoute(swigCPtr, SWIGTYPE_p_std__string.getCPtr(vehicle_id), SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(anchor_id));
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__mapT_std__string_std__string_t getVehicleInfo(SWIGTYPE_p_std__string id) {
    SWIGTYPE_p_std__mapT_std__string_std__string_t ret = new SWIGTYPE_p_std__mapT_std__string_std__string_t(CityEnginePINVOKE.Engine_getVehicleInfo(swigCPtr, SWIGTYPE_p_std__string.getCPtr(id)), true);
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
