//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Engine : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Engine(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Engine obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Engine obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Engine() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_Engine(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_std__mt19937 rnd {
    set {
      CityFlowPINVOKE.Engine_rnd_set(swigCPtr, SWIGTYPE_p_std__mt19937.getCPtr(value));
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__mt19937 ret = new SWIGTYPE_p_std__mt19937(CityFlowPINVOKE.Engine_rnd_get(swigCPtr), true);
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public Engine(string configFile, int threadNum) : this(CityFlowPINVOKE.new_Engine(configFile, threadNum), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getInterval() {
    double ret = CityFlowPINVOKE.Engine_getInterval(swigCPtr);
    return ret;
  }

  public bool hasLaneChange() {
    bool ret = CityFlowPINVOKE.Engine_hasLaneChange(swigCPtr);
    return ret;
  }

  public bool loadConfig(string configFile) {
    bool ret = CityFlowPINVOKE.Engine_loadConfig(swigCPtr, configFile);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void notifyCross() {
    CityFlowPINVOKE.Engine_notifyCross(swigCPtr);
  }

  public void nextStep() {
    CityFlowPINVOKE.Engine_nextStep(swigCPtr);
  }

  public bool checkPriority(int priority) {
    bool ret = CityFlowPINVOKE.Engine_checkPriority(swigCPtr, priority);
    return ret;
  }

  public void pushVehicle(SWIGTYPE_p_Vehicle vehicle, bool pushToDrivable) {
    CityFlowPINVOKE.Engine_pushVehicle__SWIG_0(swigCPtr, SWIGTYPE_p_Vehicle.getCPtr(vehicle), pushToDrivable);
  }

  public void pushVehicle(SWIGTYPE_p_Vehicle vehicle) {
    CityFlowPINVOKE.Engine_pushVehicle__SWIG_1(swigCPtr, SWIGTYPE_p_Vehicle.getCPtr(vehicle));
  }

  public void setLogFile(string jsonFile, string logFile) {
    CityFlowPINVOKE.Engine_setLogFile(swigCPtr, jsonFile, logFile);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void initSegments() {
    CityFlowPINVOKE.Engine_initSegments(swigCPtr);
  }

  public void pushVehicle(StringDoubleMap info, StringVector roads) {
    CityFlowPINVOKE.Engine_pushVehicle__SWIG_2(swigCPtr, StringDoubleMap.getCPtr(info), StringVector.getCPtr(roads));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint getVehicleCount() {
    uint ret = CityFlowPINVOKE.Engine_getVehicleCount(swigCPtr);
    return ret;
  }

  public StringVector getVehicles(bool includeWaiting) {
    StringVector ret = new StringVector(CityFlowPINVOKE.Engine_getVehicles__SWIG_0(swigCPtr, includeWaiting), true);
    return ret;
  }

  public StringVector getVehicles() {
    StringVector ret = new StringVector(CityFlowPINVOKE.Engine_getVehicles__SWIG_1(swigCPtr), true);
    return ret;
  }

  public StringIntMap getLaneVehicleCount() {
    StringIntMap ret = new StringIntMap(CityFlowPINVOKE.Engine_getLaneVehicleCount(swigCPtr), true);
    return ret;
  }

  public StringIntMap getLaneWaitingVehicleCount() {
    StringIntMap ret = new StringIntMap(CityFlowPINVOKE.Engine_getLaneWaitingVehicleCount(swigCPtr), true);
    return ret;
  }

  public StringStringVectorMap getLaneVehicles() {
    StringStringVectorMap ret = new StringStringVectorMap(CityFlowPINVOKE.Engine_getLaneVehicles(swigCPtr), true);
    return ret;
  }

  public StringDoubleMap getVehicleSpeed() {
    StringDoubleMap ret = new StringDoubleMap(CityFlowPINVOKE.Engine_getVehicleSpeed(swigCPtr), true);
    return ret;
  }

  public StringDoubleMap getVehicleDistance() {
    StringDoubleMap ret = new StringDoubleMap(CityFlowPINVOKE.Engine_getVehicleDistance(swigCPtr), true);
    return ret;
  }

  public string getLeader(string vehicleId) {
    string ret = CityFlowPINVOKE.Engine_getLeader(swigCPtr, vehicleId);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getCurrentTime() {
    double ret = CityFlowPINVOKE.Engine_getCurrentTime(swigCPtr);
    return ret;
  }

  public double getAverageTravelTime() {
    double ret = CityFlowPINVOKE.Engine_getAverageTravelTime(swigCPtr);
    return ret;
  }

  public void setTrafficLightPhase(string id, int phaseIndex) {
    CityFlowPINVOKE.Engine_setTrafficLightPhase(swigCPtr, id, phaseIndex);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setReplayLogFile(string logFile) {
    CityFlowPINVOKE.Engine_setReplayLogFile(swigCPtr, logFile);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setSaveReplay(bool open) {
    CityFlowPINVOKE.Engine_setSaveReplay(swigCPtr, open);
  }

  public void setVehicleSpeed(string id, double speed) {
    CityFlowPINVOKE.Engine_setVehicleSpeed(swigCPtr, id, speed);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setRandomSeed(int seed) {
    CityFlowPINVOKE.Engine_setRandomSeed(swigCPtr, seed);
  }

  public void reset(bool resetRnd) {
    CityFlowPINVOKE.Engine_reset__SWIG_0(swigCPtr, resetRnd);
  }

  public void reset() {
    CityFlowPINVOKE.Engine_reset__SWIG_1(swigCPtr);
  }

  public void load(SWIGTYPE_p_Archive archive) {
    CityFlowPINVOKE.Engine_load(swigCPtr, SWIGTYPE_p_Archive.getCPtr(archive));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Archive snapshot() {
    SWIGTYPE_p_Archive ret = new SWIGTYPE_p_Archive(CityFlowPINVOKE.Engine_snapshot(swigCPtr), true);
    return ret;
  }

  public void loadFromFile(string fileName) {
    CityFlowPINVOKE.Engine_loadFromFile(swigCPtr, fileName);
  }

  public bool setRoute(string vehicle_id, StringVector anchor_id) {
    bool ret = CityFlowPINVOKE.Engine_setRoute(swigCPtr, vehicle_id, StringVector.getCPtr(anchor_id));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public StringStringMap getVehicleInfo(string id) {
    StringStringMap ret = new StringStringMap(CityFlowPINVOKE.Engine_getVehicleInfo(swigCPtr, id), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
