//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class LaneLinkPointerVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<LaneLink>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LaneLinkPointerVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LaneLinkPointerVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LaneLinkPointerVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LaneLinkPointerVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_LaneLinkPointerVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public LaneLinkPointerVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (LaneLink element in c) {
      this.Add(element);
    }
  }

  public LaneLinkPointerVector(global::System.Collections.Generic.IEnumerable<LaneLink> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (LaneLink element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public LaneLink this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(LaneLink[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(LaneLink[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, LaneLink[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public LaneLink[] ToArray() {
    LaneLink[] array = new LaneLink[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<LaneLink> global::System.Collections.Generic.IEnumerable<LaneLink>.GetEnumerator() {
    return new LaneLinkPointerVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new LaneLinkPointerVectorEnumerator(this);
  }

  public LaneLinkPointerVectorEnumerator GetEnumerator() {
    return new LaneLinkPointerVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class LaneLinkPointerVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<LaneLink>
  {
    private LaneLinkPointerVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public LaneLinkPointerVectorEnumerator(LaneLinkPointerVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public LaneLink Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (LaneLink)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public LaneLinkPointerVector() : this(CityFlowPINVOKE.new_LaneLinkPointerVector__SWIG_0(), true) {
  }

  public LaneLinkPointerVector(LaneLinkPointerVector other) : this(CityFlowPINVOKE.new_LaneLinkPointerVector__SWIG_1(LaneLinkPointerVector.getCPtr(other)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    CityFlowPINVOKE.LaneLinkPointerVector_Clear(swigCPtr);
  }

  public void Add(LaneLink x) {
    CityFlowPINVOKE.LaneLinkPointerVector_Add(swigCPtr, LaneLink.getCPtr(x));
  }

  private uint size() {
    uint ret = CityFlowPINVOKE.LaneLinkPointerVector_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = CityFlowPINVOKE.LaneLinkPointerVector_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CityFlowPINVOKE.LaneLinkPointerVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CityFlowPINVOKE.LaneLinkPointerVector_reserve(swigCPtr, n);
  }

  public LaneLinkPointerVector(int capacity) : this(CityFlowPINVOKE.new_LaneLinkPointerVector__SWIG_2(capacity), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private LaneLink getitemcopy(int index) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.LaneLinkPointerVector_getitemcopy(swigCPtr, index);
    LaneLink ret = (cPtr == global::System.IntPtr.Zero) ? null : new LaneLink(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private LaneLink getitem(int index) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.LaneLinkPointerVector_getitem(swigCPtr, index);
    LaneLink ret = (cPtr == global::System.IntPtr.Zero) ? null : new LaneLink(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, LaneLink val) {
    CityFlowPINVOKE.LaneLinkPointerVector_setitem(swigCPtr, index, LaneLink.getCPtr(val));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(LaneLinkPointerVector values) {
    CityFlowPINVOKE.LaneLinkPointerVector_AddRange(swigCPtr, LaneLinkPointerVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public LaneLinkPointerVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.LaneLinkPointerVector_GetRange(swigCPtr, index, count);
    LaneLinkPointerVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new LaneLinkPointerVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, LaneLink x) {
    CityFlowPINVOKE.LaneLinkPointerVector_Insert(swigCPtr, index, LaneLink.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, LaneLinkPointerVector values) {
    CityFlowPINVOKE.LaneLinkPointerVector_InsertRange(swigCPtr, index, LaneLinkPointerVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CityFlowPINVOKE.LaneLinkPointerVector_RemoveAt(swigCPtr, index);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CityFlowPINVOKE.LaneLinkPointerVector_RemoveRange(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public static LaneLinkPointerVector Repeat(LaneLink value, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.LaneLinkPointerVector_Repeat(LaneLink.getCPtr(value), count);
    LaneLinkPointerVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new LaneLinkPointerVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CityFlowPINVOKE.LaneLinkPointerVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CityFlowPINVOKE.LaneLinkPointerVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, LaneLinkPointerVector values) {
    CityFlowPINVOKE.LaneLinkPointerVector_SetRange(swigCPtr, index, LaneLinkPointerVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(LaneLink value) {
    bool ret = CityFlowPINVOKE.LaneLinkPointerVector_Contains(swigCPtr, LaneLink.getCPtr(value));
    return ret;
  }

  public int IndexOf(LaneLink value) {
    int ret = CityFlowPINVOKE.LaneLinkPointerVector_IndexOf(swigCPtr, LaneLink.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(LaneLink value) {
    int ret = CityFlowPINVOKE.LaneLinkPointerVector_LastIndexOf(swigCPtr, LaneLink.getCPtr(value));
    return ret;
  }

  public bool Remove(LaneLink value) {
    bool ret = CityFlowPINVOKE.LaneLinkPointerVector_Remove(swigCPtr, LaneLink.getCPtr(value));
    return ret;
  }

}

}
