//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class LaneChange : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LaneChange(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LaneChange obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LaneChange obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LaneChange() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityEnginePINVOKE.delete_LaneChange(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public void updateLeaderAndFollower() {
    CityEnginePINVOKE.LaneChange_updateLeaderAndFollower(swigCPtr);
  }

  public Lane getTarget() {
    global::System.IntPtr cPtr = CityEnginePINVOKE.LaneChange_getTarget(swigCPtr);
    Lane ret = (cPtr == global::System.IntPtr.Zero) ? null : new Lane(cPtr, false);
    return ret;
  }

  public Vehicle getTargetLeader() {
    global::System.IntPtr cPtr = CityEnginePINVOKE.LaneChange_getTargetLeader(swigCPtr);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public Vehicle getTargetFollower() {
    global::System.IntPtr cPtr = CityEnginePINVOKE.LaneChange_getTargetFollower(swigCPtr);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public double gapBefore() {
    double ret = CityEnginePINVOKE.LaneChange_gapBefore(swigCPtr);
    return ret;
  }

  public double gapAfter() {
    double ret = CityEnginePINVOKE.LaneChange_gapAfter(swigCPtr);
    return ret;
  }

  public void insertShadow(Vehicle shadow) {
    CityEnginePINVOKE.LaneChange_insertShadow(swigCPtr, Vehicle.getCPtr(shadow));
  }

  public virtual double safeGapBefore() {
    double ret = CityEnginePINVOKE.LaneChange_safeGapBefore(swigCPtr);
    return ret;
  }

  public virtual double safeGapAfter() {
    double ret = CityEnginePINVOKE.LaneChange_safeGapAfter(swigCPtr);
    return ret;
  }

  public virtual void makeSignal(double interval) {
    CityEnginePINVOKE.LaneChange_makeSignal(swigCPtr, interval);
  }

  public bool planChange() {
    bool ret = CityEnginePINVOKE.LaneChange_planChange(swigCPtr);
    return ret;
  }

  public bool canChange() {
    bool ret = CityEnginePINVOKE.LaneChange_canChange(swigCPtr);
    return ret;
  }

  public bool isGapValid() {
    bool ret = CityEnginePINVOKE.LaneChange_isGapValid(swigCPtr);
    return ret;
  }

  public void finishChanging() {
    CityEnginePINVOKE.LaneChange_finishChanging(swigCPtr);
  }

  public void abortChanging() {
    CityEnginePINVOKE.LaneChange_abortChanging(swigCPtr);
  }

  public virtual double yieldSpeed(double interval) {
    double ret = CityEnginePINVOKE.LaneChange_yieldSpeed(swigCPtr, interval);
    return ret;
  }

  public virtual void sendSignal() {
    CityEnginePINVOKE.LaneChange_sendSignal(swigCPtr);
  }

  public int getDirection() {
    int ret = CityEnginePINVOKE.LaneChange_getDirection(swigCPtr);
    return ret;
  }

  public void clearSignal() {
    CityEnginePINVOKE.LaneChange_clearSignal(swigCPtr);
  }

  public bool hasFinished() {
    bool ret = CityEnginePINVOKE.LaneChange_hasFinished(swigCPtr);
    return ret;
  }

}

}
