//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class LanePointerVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<Lane>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LanePointerVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LanePointerVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LanePointerVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LanePointerVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_LanePointerVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public LanePointerVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Lane element in c) {
      this.Add(element);
    }
  }

  public LanePointerVector(global::System.Collections.Generic.IEnumerable<Lane> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Lane element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Lane this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Lane[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Lane[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Lane[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Lane[] ToArray() {
    Lane[] array = new Lane[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Lane> global::System.Collections.Generic.IEnumerable<Lane>.GetEnumerator() {
    return new LanePointerVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new LanePointerVectorEnumerator(this);
  }

  public LanePointerVectorEnumerator GetEnumerator() {
    return new LanePointerVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class LanePointerVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Lane>
  {
    private LanePointerVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public LanePointerVectorEnumerator(LanePointerVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Lane Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Lane)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public LanePointerVector() : this(CityFlowPINVOKE.new_LanePointerVector__SWIG_0(), true) {
  }

  public LanePointerVector(LanePointerVector other) : this(CityFlowPINVOKE.new_LanePointerVector__SWIG_1(LanePointerVector.getCPtr(other)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    CityFlowPINVOKE.LanePointerVector_Clear(swigCPtr);
  }

  public void Add(Lane x) {
    CityFlowPINVOKE.LanePointerVector_Add(swigCPtr, Lane.getCPtr(x));
  }

  private uint size() {
    uint ret = CityFlowPINVOKE.LanePointerVector_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = CityFlowPINVOKE.LanePointerVector_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CityFlowPINVOKE.LanePointerVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CityFlowPINVOKE.LanePointerVector_reserve(swigCPtr, n);
  }

  public LanePointerVector(int capacity) : this(CityFlowPINVOKE.new_LanePointerVector__SWIG_2(capacity), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private Lane getitemcopy(int index) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.LanePointerVector_getitemcopy(swigCPtr, index);
    Lane ret = (cPtr == global::System.IntPtr.Zero) ? null : new Lane(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Lane getitem(int index) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.LanePointerVector_getitem(swigCPtr, index);
    Lane ret = (cPtr == global::System.IntPtr.Zero) ? null : new Lane(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Lane val) {
    CityFlowPINVOKE.LanePointerVector_setitem(swigCPtr, index, Lane.getCPtr(val));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(LanePointerVector values) {
    CityFlowPINVOKE.LanePointerVector_AddRange(swigCPtr, LanePointerVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public LanePointerVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.LanePointerVector_GetRange(swigCPtr, index, count);
    LanePointerVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new LanePointerVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Lane x) {
    CityFlowPINVOKE.LanePointerVector_Insert(swigCPtr, index, Lane.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, LanePointerVector values) {
    CityFlowPINVOKE.LanePointerVector_InsertRange(swigCPtr, index, LanePointerVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CityFlowPINVOKE.LanePointerVector_RemoveAt(swigCPtr, index);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CityFlowPINVOKE.LanePointerVector_RemoveRange(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public static LanePointerVector Repeat(Lane value, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.LanePointerVector_Repeat(Lane.getCPtr(value), count);
    LanePointerVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new LanePointerVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CityFlowPINVOKE.LanePointerVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CityFlowPINVOKE.LanePointerVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, LanePointerVector values) {
    CityFlowPINVOKE.LanePointerVector_SetRange(swigCPtr, index, LanePointerVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(Lane value) {
    bool ret = CityFlowPINVOKE.LanePointerVector_Contains(swigCPtr, Lane.getCPtr(value));
    return ret;
  }

  public int IndexOf(Lane value) {
    int ret = CityFlowPINVOKE.LanePointerVector_IndexOf(swigCPtr, Lane.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(Lane value) {
    int ret = CityFlowPINVOKE.LanePointerVector_LastIndexOf(swigCPtr, Lane.getCPtr(value));
    return ret;
  }

  public bool Remove(Lane value) {
    bool ret = CityFlowPINVOKE.LanePointerVector_Remove(swigCPtr, Lane.getCPtr(value));
    return ret;
  }

}

}
