//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class OptionParser : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OptionParser(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OptionParser obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OptionParser obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~OptionParser() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityEnginePINVOKE.delete_OptionParser(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public OptionParser(SWIGTYPE_p_std__string description, bool create_help) : this(CityEnginePINVOKE.new_OptionParser__SWIG_0(SWIGTYPE_p_std__string.getCPtr(description), create_help), true) {
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public OptionParser(SWIGTYPE_p_std__string description) : this(CityEnginePINVOKE.new_OptionParser__SWIG_1(SWIGTYPE_p_std__string.getCPtr(description)), true) {
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public OptionParser() : this(CityEnginePINVOKE.new_OptionParser__SWIG_2(), true) {
  }

  public void eat_arguments(uint argc, SWIGTYPE_p_p_char argv) {
    CityEnginePINVOKE.OptionParser_eat_arguments(swigCPtr, argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public Option add_option(SWIGTYPE_p_std__string first_option, SWIGTYPE_p_std__string second_option) {
    Option ret = new Option(CityEnginePINVOKE.OptionParser_add_option__SWIG_0(swigCPtr, SWIGTYPE_p_std__string.getCPtr(first_option), SWIGTYPE_p_std__string.getCPtr(second_option)), false);
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Option add_option(SWIGTYPE_p_std__string first_option) {
    Option ret = new Option(CityEnginePINVOKE.OptionParser_add_option__SWIG_1(swigCPtr, SWIGTYPE_p_std__string.getCPtr(first_option)), false);
    if (CityEnginePINVOKE.SWIGPendingException.Pending) throw CityEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void help() {
    CityEnginePINVOKE.OptionParser_help(swigCPtr);
  }

}

}
