//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class RoadVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<Road>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RoadVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RoadVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RoadVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RoadVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_RoadVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public RoadVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Road element in c) {
      this.Add(element);
    }
  }

  public RoadVector(global::System.Collections.Generic.IEnumerable<Road> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Road element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Road this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Road[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Road[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Road[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Road[] ToArray() {
    Road[] array = new Road[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Road> global::System.Collections.Generic.IEnumerable<Road>.GetEnumerator() {
    return new RoadVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new RoadVectorEnumerator(this);
  }

  public RoadVectorEnumerator GetEnumerator() {
    return new RoadVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class RoadVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Road>
  {
    private RoadVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public RoadVectorEnumerator(RoadVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Road Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Road)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public RoadVector() : this(CityFlowPINVOKE.new_RoadVector__SWIG_0(), true) {
  }

  public RoadVector(RoadVector other) : this(CityFlowPINVOKE.new_RoadVector__SWIG_1(RoadVector.getCPtr(other)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    CityFlowPINVOKE.RoadVector_Clear(swigCPtr);
  }

  public void Add(Road x) {
    CityFlowPINVOKE.RoadVector_Add(swigCPtr, Road.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = CityFlowPINVOKE.RoadVector_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = CityFlowPINVOKE.RoadVector_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CityFlowPINVOKE.RoadVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CityFlowPINVOKE.RoadVector_reserve(swigCPtr, n);
  }

  public RoadVector(int capacity) : this(CityFlowPINVOKE.new_RoadVector__SWIG_2(capacity), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private Road getitemcopy(int index) {
    Road ret = new Road(CityFlowPINVOKE.RoadVector_getitemcopy(swigCPtr, index), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Road getitem(int index) {
    Road ret = new Road(CityFlowPINVOKE.RoadVector_getitem(swigCPtr, index), false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Road val) {
    CityFlowPINVOKE.RoadVector_setitem(swigCPtr, index, Road.getCPtr(val));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(RoadVector values) {
    CityFlowPINVOKE.RoadVector_AddRange(swigCPtr, RoadVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public RoadVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.RoadVector_GetRange(swigCPtr, index, count);
    RoadVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new RoadVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Road x) {
    CityFlowPINVOKE.RoadVector_Insert(swigCPtr, index, Road.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, RoadVector values) {
    CityFlowPINVOKE.RoadVector_InsertRange(swigCPtr, index, RoadVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CityFlowPINVOKE.RoadVector_RemoveAt(swigCPtr, index);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CityFlowPINVOKE.RoadVector_RemoveRange(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public static RoadVector Repeat(Road value, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.RoadVector_Repeat(Road.getCPtr(value), count);
    RoadVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new RoadVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CityFlowPINVOKE.RoadVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CityFlowPINVOKE.RoadVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, RoadVector values) {
    CityFlowPINVOKE.RoadVector_SetRange(swigCPtr, index, RoadVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
