//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class RoadLinkVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<SWIGTYPE_p_RoadLink>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RoadLinkVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RoadLinkVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RoadLinkVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RoadLinkVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_RoadLinkVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public RoadLinkVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (SWIGTYPE_p_RoadLink element in c) {
      this.Add(element);
    }
  }

  public RoadLinkVector(global::System.Collections.Generic.IEnumerable<SWIGTYPE_p_RoadLink> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (SWIGTYPE_p_RoadLink element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public SWIGTYPE_p_RoadLink this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(SWIGTYPE_p_RoadLink[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(SWIGTYPE_p_RoadLink[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, SWIGTYPE_p_RoadLink[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public SWIGTYPE_p_RoadLink[] ToArray() {
    SWIGTYPE_p_RoadLink[] array = new SWIGTYPE_p_RoadLink[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<SWIGTYPE_p_RoadLink> global::System.Collections.Generic.IEnumerable<SWIGTYPE_p_RoadLink>.GetEnumerator() {
    return new RoadLinkVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new RoadLinkVectorEnumerator(this);
  }

  public RoadLinkVectorEnumerator GetEnumerator() {
    return new RoadLinkVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class RoadLinkVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<SWIGTYPE_p_RoadLink>
  {
    private RoadLinkVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public RoadLinkVectorEnumerator(RoadLinkVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public SWIGTYPE_p_RoadLink Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (SWIGTYPE_p_RoadLink)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public RoadLinkVector() : this(CityFlowPINVOKE.new_RoadLinkVector__SWIG_0(), true) {
  }

  public RoadLinkVector(RoadLinkVector other) : this(CityFlowPINVOKE.new_RoadLinkVector__SWIG_1(RoadLinkVector.getCPtr(other)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    CityFlowPINVOKE.RoadLinkVector_Clear(swigCPtr);
  }

  public void Add(SWIGTYPE_p_RoadLink x) {
    CityFlowPINVOKE.RoadLinkVector_Add(swigCPtr, SWIGTYPE_p_RoadLink.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = CityFlowPINVOKE.RoadLinkVector_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = CityFlowPINVOKE.RoadLinkVector_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CityFlowPINVOKE.RoadLinkVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CityFlowPINVOKE.RoadLinkVector_reserve(swigCPtr, n);
  }

  public RoadLinkVector(int capacity) : this(CityFlowPINVOKE.new_RoadLinkVector__SWIG_2(capacity), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private SWIGTYPE_p_RoadLink getitemcopy(int index) {
    SWIGTYPE_p_RoadLink ret = new SWIGTYPE_p_RoadLink(CityFlowPINVOKE.RoadLinkVector_getitemcopy(swigCPtr, index), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private SWIGTYPE_p_RoadLink getitem(int index) {
    SWIGTYPE_p_RoadLink ret = new SWIGTYPE_p_RoadLink(CityFlowPINVOKE.RoadLinkVector_getitem(swigCPtr, index), false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, SWIGTYPE_p_RoadLink val) {
    CityFlowPINVOKE.RoadLinkVector_setitem(swigCPtr, index, SWIGTYPE_p_RoadLink.getCPtr(val));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(RoadLinkVector values) {
    CityFlowPINVOKE.RoadLinkVector_AddRange(swigCPtr, RoadLinkVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public RoadLinkVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.RoadLinkVector_GetRange(swigCPtr, index, count);
    RoadLinkVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new RoadLinkVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, SWIGTYPE_p_RoadLink x) {
    CityFlowPINVOKE.RoadLinkVector_Insert(swigCPtr, index, SWIGTYPE_p_RoadLink.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, RoadLinkVector values) {
    CityFlowPINVOKE.RoadLinkVector_InsertRange(swigCPtr, index, RoadLinkVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CityFlowPINVOKE.RoadLinkVector_RemoveAt(swigCPtr, index);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CityFlowPINVOKE.RoadLinkVector_RemoveRange(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public static RoadLinkVector Repeat(SWIGTYPE_p_RoadLink value, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.RoadLinkVector_Repeat(SWIGTYPE_p_RoadLink.getCPtr(value), count);
    RoadLinkVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new RoadLinkVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CityFlowPINVOKE.RoadLinkVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CityFlowPINVOKE.RoadLinkVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, RoadLinkVector values) {
    CityFlowPINVOKE.RoadLinkVector_SetRange(swigCPtr, index, RoadLinkVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
