//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class VehicleDeque : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VehicleDeque(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VehicleDeque obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VehicleDeque obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VehicleDeque() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_VehicleDeque(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool empty() {
    bool ret = CityFlowPINVOKE.VehicleDeque_empty(swigCPtr);
    return ret;
  }

  public VehicleDeque() : this(CityFlowPINVOKE.new_VehicleDeque__SWIG_0(), true) {
  }

  public VehicleDeque(uint size, Vehicle value) : this(CityFlowPINVOKE.new_VehicleDeque__SWIG_1(size, Vehicle.getCPtr(value)), true) {
  }

  public VehicleDeque(uint size) : this(CityFlowPINVOKE.new_VehicleDeque__SWIG_2(size), true) {
  }

  public VehicleDeque(VehicleDeque arg0) : this(CityFlowPINVOKE.new_VehicleDeque__SWIG_3(VehicleDeque.getCPtr(arg0)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void assign(uint n, Vehicle value) {
    CityFlowPINVOKE.VehicleDeque_assign(swigCPtr, n, Vehicle.getCPtr(value));
  }

  public void swap(VehicleDeque x) {
    CityFlowPINVOKE.VehicleDeque_swap(swigCPtr, VehicleDeque.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint size() {
    uint ret = CityFlowPINVOKE.VehicleDeque_size(swigCPtr);
    return ret;
  }

  public uint max_size() {
    uint ret = CityFlowPINVOKE.VehicleDeque_max_size(swigCPtr);
    return ret;
  }

  public void resize(uint n, Vehicle c) {
    CityFlowPINVOKE.VehicleDeque_resize__SWIG_0(swigCPtr, n, Vehicle.getCPtr(c));
  }

  public void resize(uint n) {
    CityFlowPINVOKE.VehicleDeque_resize__SWIG_1(swigCPtr, n);
  }

  public Vehicle front() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.VehicleDeque_front(swigCPtr);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public Vehicle back() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.VehicleDeque_back(swigCPtr);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public void push_front(Vehicle x) {
    CityFlowPINVOKE.VehicleDeque_push_front(swigCPtr, Vehicle.getCPtr(x));
  }

  public void push_back(Vehicle x) {
    CityFlowPINVOKE.VehicleDeque_push_back(swigCPtr, Vehicle.getCPtr(x));
  }

  public void pop_front() {
    CityFlowPINVOKE.VehicleDeque_pop_front(swigCPtr);
  }

  public void pop_back() {
    CityFlowPINVOKE.VehicleDeque_pop_back(swigCPtr);
  }

  public void clear() {
    CityFlowPINVOKE.VehicleDeque_clear(swigCPtr);
  }

  public Vehicle getitem(int i) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.VehicleDeque_getitem(swigCPtr, i);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setitem(int i, Vehicle x) {
    CityFlowPINVOKE.VehicleDeque_setitem(swigCPtr, i, Vehicle.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void delitem(int i) {
    CityFlowPINVOKE.VehicleDeque_delitem(swigCPtr, i);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public VehicleDeque getslice(int i, int j) {
    VehicleDeque ret = new VehicleDeque(CityFlowPINVOKE.VehicleDeque_getslice(swigCPtr, i, j), true);
    return ret;
  }

  public void setslice(int i, int j, VehicleDeque v) {
    CityFlowPINVOKE.VehicleDeque_setslice(swigCPtr, i, j, VehicleDeque.getCPtr(v));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void delslice(int i, int j) {
    CityFlowPINVOKE.VehicleDeque_delslice(swigCPtr, i, j);
  }

}

}
