//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class VehicleVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<Vehicle>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VehicleVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VehicleVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VehicleVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VehicleVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_VehicleVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VehicleVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Vehicle element in c) {
      this.Add(element);
    }
  }

  public VehicleVector(global::System.Collections.Generic.IEnumerable<Vehicle> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Vehicle element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Vehicle this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Vehicle[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Vehicle[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Vehicle[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Vehicle[] ToArray() {
    Vehicle[] array = new Vehicle[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Vehicle> global::System.Collections.Generic.IEnumerable<Vehicle>.GetEnumerator() {
    return new VehicleVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VehicleVectorEnumerator(this);
  }

  public VehicleVectorEnumerator GetEnumerator() {
    return new VehicleVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VehicleVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Vehicle>
  {
    private VehicleVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VehicleVectorEnumerator(VehicleVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Vehicle Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Vehicle)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VehicleVector() : this(CityFlowPINVOKE.new_VehicleVector__SWIG_0(), true) {
  }

  public VehicleVector(VehicleVector other) : this(CityFlowPINVOKE.new_VehicleVector__SWIG_1(VehicleVector.getCPtr(other)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    CityFlowPINVOKE.VehicleVector_Clear(swigCPtr);
  }

  public void Add(Vehicle x) {
    CityFlowPINVOKE.VehicleVector_Add(swigCPtr, Vehicle.getCPtr(x));
  }

  private uint size() {
    uint ret = CityFlowPINVOKE.VehicleVector_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = CityFlowPINVOKE.VehicleVector_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CityFlowPINVOKE.VehicleVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CityFlowPINVOKE.VehicleVector_reserve(swigCPtr, n);
  }

  public VehicleVector(int capacity) : this(CityFlowPINVOKE.new_VehicleVector__SWIG_2(capacity), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private Vehicle getitemcopy(int index) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.VehicleVector_getitemcopy(swigCPtr, index);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Vehicle getitem(int index) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.VehicleVector_getitem(swigCPtr, index);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Vehicle val) {
    CityFlowPINVOKE.VehicleVector_setitem(swigCPtr, index, Vehicle.getCPtr(val));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VehicleVector values) {
    CityFlowPINVOKE.VehicleVector_AddRange(swigCPtr, VehicleVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public VehicleVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.VehicleVector_GetRange(swigCPtr, index, count);
    VehicleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new VehicleVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Vehicle x) {
    CityFlowPINVOKE.VehicleVector_Insert(swigCPtr, index, Vehicle.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VehicleVector values) {
    CityFlowPINVOKE.VehicleVector_InsertRange(swigCPtr, index, VehicleVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CityFlowPINVOKE.VehicleVector_RemoveAt(swigCPtr, index);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CityFlowPINVOKE.VehicleVector_RemoveRange(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VehicleVector Repeat(Vehicle value, int count) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.VehicleVector_Repeat(Vehicle.getCPtr(value), count);
    VehicleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new VehicleVector(cPtr, true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CityFlowPINVOKE.VehicleVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CityFlowPINVOKE.VehicleVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VehicleVector values) {
    CityFlowPINVOKE.VehicleVector_SetRange(swigCPtr, index, VehicleVector.getCPtr(values));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(Vehicle value) {
    bool ret = CityFlowPINVOKE.VehicleVector_Contains(swigCPtr, Vehicle.getCPtr(value));
    return ret;
  }

  public int IndexOf(Vehicle value) {
    int ret = CityFlowPINVOKE.VehicleVector_IndexOf(swigCPtr, Vehicle.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(Vehicle value) {
    int ret = CityFlowPINVOKE.VehicleVector_LastIndexOf(swigCPtr, Vehicle.getCPtr(value));
    return ret;
  }

  public bool Remove(Vehicle value) {
    bool ret = CityFlowPINVOKE.VehicleVector_Remove(swigCPtr, Vehicle.getCPtr(value));
    return ret;
  }

}

}
