//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class VehicleListList : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<VehicleList>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VehicleListList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VehicleListList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VehicleListList obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VehicleListList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_VehicleListList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VehicleListList(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VehicleList element in c) {
      this.AddLast(element);
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public VehicleListListNode First {
    get {
      if (Count == 0)
        return null;
      return new VehicleListListNode(getFirstIter(), this);
    }
  }

  public VehicleListListNode Last {
    get {
      if (Count == 0)
        return null;
      return new VehicleListListNode(getLastIter(), this);
    }
  }

  public VehicleListListNode AddFirst(VehicleList value) {
    push_front(value);
    return new VehicleListListNode(getFirstIter(), this);
  }

  public void AddFirst(VehicleListListNode newNode) {
    ValidateNewNode(newNode);
    if (!newNode.inlist) {
      push_front(newNode.csharpvalue);
      newNode.iter = getFirstIter();
      newNode.inlist = true;
    } else {
      throw new global::System.InvalidOperationException("The " + newNode.GetType().Name + " node already belongs to a " + this.GetType().Name);
    }
  }

  public VehicleListListNode AddLast(VehicleList value) {
    push_back(value);
    return new VehicleListListNode(getLastIter(), this);
  }

  public void AddLast(VehicleListListNode newNode) {
    ValidateNewNode(newNode);
    if (!newNode.inlist) {
      push_back(newNode.csharpvalue);
      newNode.iter = getLastIter();
      newNode.inlist = true;
    } else {
      throw new global::System.InvalidOperationException("The " + newNode.GetType().Name + " node already belongs to a " + this.GetType().Name);
    }
  }

  public VehicleListListNode AddBefore(VehicleListListNode node, VehicleList value) {
    return new VehicleListListNode(insertNode(node.iter, value), this);
  }

  public void AddBefore(VehicleListListNode node, VehicleListListNode newNode) {
    ValidateNode(node);
    ValidateNewNode(newNode);
    if (!newNode.inlist) {
      newNode.iter = insertNode(node.iter, newNode.csharpvalue);
      newNode.inlist = true;
    } else {
      throw new global::System.InvalidOperationException("The " + newNode.GetType().Name + " node already belongs to a " + this.GetType().Name);
    }
  }

  public VehicleListListNode AddAfter(VehicleListListNode node, VehicleList value) {
    node = node.Next;
    return new VehicleListListNode(insertNode(node.iter, value), this);
  }

  public void AddAfter(VehicleListListNode node, VehicleListListNode newNode) {
    ValidateNode(node);
    ValidateNewNode(newNode);
    if (!newNode.inlist) {
      if (node == this.Last)
        AddLast(newNode);
      else
      {
        node = node.Next;
        newNode.iter = insertNode(node.iter, newNode.csharpvalue);
        newNode.inlist = true;
      }
    } else {
      throw new global::System.InvalidOperationException("The " + newNode.GetType().Name + " node already belongs to a " + this.GetType().Name);
    }
  }

  public void Add(VehicleList value) {
    AddLast(value);
  }

  public void Remove(VehicleListListNode node) {
    ValidateNode(node);
    eraseIter(node.iter);
  }

  public void CopyTo(VehicleList[] array, int index) {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0 || index > array.Length)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    VehicleListListNode node = this.First;
    if (node != null) {
      do {
        array[index++] = node.Value;
        node = node.Next;
      } while (node != null);
    }
  }

  internal void ValidateNode(VehicleListListNode node) {
    if (node == null) {
      throw new System.ArgumentNullException("node");
    }
    if (!node.inlist || node.list != this) {
      throw new System.InvalidOperationException("node");
    }
  }

  internal void ValidateNewNode(VehicleListListNode node) {
    if (node == null) {
      throw new System.ArgumentNullException("node");
    }
  }

  global::System.Collections.Generic.IEnumerator<VehicleList> global::System.Collections.Generic.IEnumerable<VehicleList>.GetEnumerator() {
    return new VehicleListListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VehicleListListEnumerator(this);
  }

  public VehicleListListEnumerator GetEnumerator() {
    return new VehicleListListEnumerator(this);
  }

  public sealed class VehicleListListEnumerator : global::System.Collections.IEnumerator,
    global::System.Collections.Generic.IEnumerator<VehicleList>
  {
    private VehicleListList collectionRef;
    private VehicleListListNode currentNode;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VehicleListListEnumerator(VehicleListList collection) {
      collectionRef = collection;
      currentNode = collection.First;
      currentIndex = 0;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public VehicleList Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (VehicleList)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      if (currentNode == null) {
        currentIndex = collectionRef.Count + 1;
        return false;
      }
      ++currentIndex;
      currentObject = currentNode.Value;
      currentNode = currentNode.Next;
      return true;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
      currentIndex = -1;
      currentObject = null;
    }
  }

  public sealed class VehicleListListNode {
    internal VehicleListList list;
    internal System.IntPtr iter;
    internal VehicleList csharpvalue;
    internal bool inlist;

    public VehicleListListNode(VehicleList value) {
      csharpvalue = value;
      inlist = false;
    }

    internal VehicleListListNode(System.IntPtr iter, VehicleListList list) {
      this.list = list;
      this.iter = iter;
      inlist = true;
    }

    public VehicleListList List {
      get {
        return this.list;
      }
    }

    public VehicleListListNode Next {
      get {
        if (list.getNextIter(iter) == System.IntPtr.Zero)
          return null;
        return new VehicleListListNode(list.getNextIter(iter), list);
      }
    }

    public VehicleListListNode Previous {
      get {
        if (list.getPrevIter(iter) == System.IntPtr.Zero)
          return null;
        return new VehicleListListNode(list.getPrevIter(iter), list);
      }
    }

    public VehicleList Value {
      get {
        return list.getItem(this.iter);
      }
      set {
        list.setItem(this.iter, value);
      }
    }

    public static bool operator==(VehicleListListNode node1, VehicleListListNode node2) {
      if (object.ReferenceEquals(node1, null) && object.ReferenceEquals(node2, null))
        return true;
      if (object.ReferenceEquals(node1, null) || object.ReferenceEquals(node2, null))
        return false;
      return node1.Equals(node2);
    }

    public static bool operator!=(VehicleListListNode node1, VehicleListListNode node2) {
      if (node1 == null && node2 == null)
        return false;
      if (node1 == null || node2 == null)
        return true;
      return !node1.Equals(node2);
    }

    public bool Equals(VehicleListListNode node) {
      if (node == null)
        return false;
      if (!node.inlist || !this.inlist)
        return object.ReferenceEquals(this, node);
      return list.equals(this.iter, node.iter);
    }

    public override bool Equals(object node) {
      return Equals((VehicleListListNode)node);
    }

    public override int GetHashCode() {
      int hash = 13;
      if (inlist) {
        hash = (hash * 7) + this.list.GetHashCode();
        hash = (hash * 7) + this.Value.GetHashCode();
        hash = (hash * 7) + this.list.getNextIter(this.iter).GetHashCode();
        hash = (hash * 7) + this.list.getPrevIter(this.iter).GetHashCode();
      } else {
        hash = (hash * 7) + this.csharpvalue.GetHashCode();
      }
      return hash;
    }

    public void Dispose() {
      list.deleteIter(this.iter);
    }
  }

  private void push_front(VehicleList x) {
    CityFlowPINVOKE.VehicleListList_push_front(swigCPtr, VehicleList.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private void push_back(VehicleList x) {
    CityFlowPINVOKE.VehicleListList_push_back(swigCPtr, VehicleList.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveFirst() {
    CityFlowPINVOKE.VehicleListList_RemoveFirst(swigCPtr);
  }

  public void RemoveLast() {
    CityFlowPINVOKE.VehicleListList_RemoveLast(swigCPtr);
  }

  private uint size() {
    uint ret = CityFlowPINVOKE.VehicleListList_size(swigCPtr);
    return ret;
  }

  public void Clear() {
    CityFlowPINVOKE.VehicleListList_Clear(swigCPtr);
  }

  private VehicleList getItem(global::System.IntPtr iter) {
    VehicleList ret = new VehicleList(CityFlowPINVOKE.VehicleListList_getItem(swigCPtr, iter), false);
    return ret;
  }

  private void setItem(global::System.IntPtr iter, VehicleList val) {
    CityFlowPINVOKE.VehicleListList_setItem(swigCPtr, iter, VehicleList.getCPtr(val));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private global::System.IntPtr getFirstIter() {
    global::System.IntPtr ret = CityFlowPINVOKE.VehicleListList_getFirstIter(swigCPtr);
    return ret;
  }

  private global::System.IntPtr getLastIter() {
    global::System.IntPtr ret = CityFlowPINVOKE.VehicleListList_getLastIter(swigCPtr);
    return ret;
  }

  private global::System.IntPtr getNextIter(global::System.IntPtr iter) {
    global::System.IntPtr ret = CityFlowPINVOKE.VehicleListList_getNextIter(swigCPtr, iter);
    return ret;
  }

  private global::System.IntPtr getPrevIter(global::System.IntPtr iter) {
    global::System.IntPtr ret = CityFlowPINVOKE.VehicleListList_getPrevIter(swigCPtr, iter);
    return ret;
  }

  public global::System.IntPtr insertNode(global::System.IntPtr iter, VehicleList value) {
    global::System.IntPtr ret = CityFlowPINVOKE.VehicleListList_insertNode(swigCPtr, iter, VehicleList.getCPtr(value));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void eraseIter(global::System.IntPtr iter) {
    CityFlowPINVOKE.VehicleListList_eraseIter(swigCPtr, iter);
  }

  private void deleteIter(global::System.IntPtr iter) {
    CityFlowPINVOKE.VehicleListList_deleteIter(swigCPtr, iter);
  }

  public bool equals(global::System.IntPtr iter1, global::System.IntPtr iter2) {
    bool ret = CityFlowPINVOKE.VehicleListList_equals(swigCPtr, iter1, iter2);
    return ret;
  }

  public VehicleListList() : this(CityFlowPINVOKE.new_VehicleListList(), true) {
  }

}

}
