//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class VehicleList : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<Vehicle>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VehicleList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VehicleList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VehicleList obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VehicleList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_VehicleList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VehicleList(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Vehicle element in c) {
      this.AddLast(element);
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public VehicleListNode First {
    get {
      if (Count == 0)
        return null;
      return new VehicleListNode(getFirstIter(), this);
    }
  }

  public VehicleListNode Last {
    get {
      if (Count == 0)
        return null;
      return new VehicleListNode(getLastIter(), this);
    }
  }

  public VehicleListNode AddFirst(Vehicle value) {
    push_front(value);
    return new VehicleListNode(getFirstIter(), this);
  }

  public void AddFirst(VehicleListNode newNode) {
    ValidateNewNode(newNode);
    if (!newNode.inlist) {
      push_front(newNode.csharpvalue);
      newNode.iter = getFirstIter();
      newNode.inlist = true;
    } else {
      throw new global::System.InvalidOperationException("The " + newNode.GetType().Name + " node already belongs to a " + this.GetType().Name);
    }
  }

  public VehicleListNode AddLast(Vehicle value) {
    push_back(value);
    return new VehicleListNode(getLastIter(), this);
  }

  public void AddLast(VehicleListNode newNode) {
    ValidateNewNode(newNode);
    if (!newNode.inlist) {
      push_back(newNode.csharpvalue);
      newNode.iter = getLastIter();
      newNode.inlist = true;
    } else {
      throw new global::System.InvalidOperationException("The " + newNode.GetType().Name + " node already belongs to a " + this.GetType().Name);
    }
  }

  public VehicleListNode AddBefore(VehicleListNode node, Vehicle value) {
    return new VehicleListNode(insertNode(node.iter, value), this);
  }

  public void AddBefore(VehicleListNode node, VehicleListNode newNode) {
    ValidateNode(node);
    ValidateNewNode(newNode);
    if (!newNode.inlist) {
      newNode.iter = insertNode(node.iter, newNode.csharpvalue);
      newNode.inlist = true;
    } else {
      throw new global::System.InvalidOperationException("The " + newNode.GetType().Name + " node already belongs to a " + this.GetType().Name);
    }
  }

  public VehicleListNode AddAfter(VehicleListNode node, Vehicle value) {
    node = node.Next;
    return new VehicleListNode(insertNode(node.iter, value), this);
  }

  public void AddAfter(VehicleListNode node, VehicleListNode newNode) {
    ValidateNode(node);
    ValidateNewNode(newNode);
    if (!newNode.inlist) {
      if (node == this.Last)
        AddLast(newNode);
      else
      {
        node = node.Next;
        newNode.iter = insertNode(node.iter, newNode.csharpvalue);
        newNode.inlist = true;
      }
    } else {
      throw new global::System.InvalidOperationException("The " + newNode.GetType().Name + " node already belongs to a " + this.GetType().Name);
    }
  }

  public void Add(Vehicle value) {
    AddLast(value);
  }

  public void Remove(VehicleListNode node) {
    ValidateNode(node);
    eraseIter(node.iter);
  }

  public void CopyTo(Vehicle[] array, int index) {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0 || index > array.Length)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    VehicleListNode node = this.First;
    if (node != null) {
      do {
        array[index++] = node.Value;
        node = node.Next;
      } while (node != null);
    }
  }

  internal void ValidateNode(VehicleListNode node) {
    if (node == null) {
      throw new System.ArgumentNullException("node");
    }
    if (!node.inlist || node.list != this) {
      throw new System.InvalidOperationException("node");
    }
  }

  internal void ValidateNewNode(VehicleListNode node) {
    if (node == null) {
      throw new System.ArgumentNullException("node");
    }
  }

  global::System.Collections.Generic.IEnumerator<Vehicle> global::System.Collections.Generic.IEnumerable<Vehicle>.GetEnumerator() {
    return new VehicleListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VehicleListEnumerator(this);
  }

  public VehicleListEnumerator GetEnumerator() {
    return new VehicleListEnumerator(this);
  }

  public sealed class VehicleListEnumerator : global::System.Collections.IEnumerator,
    global::System.Collections.Generic.IEnumerator<Vehicle>
  {
    private VehicleList collectionRef;
    private VehicleListNode currentNode;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VehicleListEnumerator(VehicleList collection) {
      collectionRef = collection;
      currentNode = collection.First;
      currentIndex = 0;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Vehicle Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Vehicle)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      if (currentNode == null) {
        currentIndex = collectionRef.Count + 1;
        return false;
      }
      ++currentIndex;
      currentObject = currentNode.Value;
      currentNode = currentNode.Next;
      return true;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
      currentIndex = -1;
      currentObject = null;
    }
  }

  public sealed class VehicleListNode {
    internal VehicleList list;
    internal System.IntPtr iter;
    internal Vehicle csharpvalue;
    internal bool inlist;

    public VehicleListNode(Vehicle value) {
      csharpvalue = value;
      inlist = false;
    }

    internal VehicleListNode(System.IntPtr iter, VehicleList list) {
      this.list = list;
      this.iter = iter;
      inlist = true;
    }

    public VehicleList List {
      get {
        return this.list;
      }
    }

    public VehicleListNode Next {
      get {
        if (list.getNextIter(iter) == System.IntPtr.Zero)
          return null;
        return new VehicleListNode(list.getNextIter(iter), list);
      }
    }

    public VehicleListNode Previous {
      get {
        if (list.getPrevIter(iter) == System.IntPtr.Zero)
          return null;
        return new VehicleListNode(list.getPrevIter(iter), list);
      }
    }

    public Vehicle Value {
      get {
        return list.getItem(this.iter);
      }
      set {
        list.setItem(this.iter, value);
      }
    }

    public static bool operator==(VehicleListNode node1, VehicleListNode node2) {
      if (object.ReferenceEquals(node1, null) && object.ReferenceEquals(node2, null))
        return true;
      if (object.ReferenceEquals(node1, null) || object.ReferenceEquals(node2, null))
        return false;
      return node1.Equals(node2);
    }

    public static bool operator!=(VehicleListNode node1, VehicleListNode node2) {
      if (node1 == null && node2 == null)
        return false;
      if (node1 == null || node2 == null)
        return true;
      return !node1.Equals(node2);
    }

    public bool Equals(VehicleListNode node) {
      if (node == null)
        return false;
      if (!node.inlist || !this.inlist)
        return object.ReferenceEquals(this, node);
      return list.equals(this.iter, node.iter);
    }

    public override bool Equals(object node) {
      return Equals((VehicleListNode)node);
    }

    public override int GetHashCode() {
      int hash = 13;
      if (inlist) {
        hash = (hash * 7) + this.list.GetHashCode();
        hash = (hash * 7) + this.Value.GetHashCode();
        hash = (hash * 7) + this.list.getNextIter(this.iter).GetHashCode();
        hash = (hash * 7) + this.list.getPrevIter(this.iter).GetHashCode();
      } else {
        hash = (hash * 7) + this.csharpvalue.GetHashCode();
      }
      return hash;
    }

    public void Dispose() {
      list.deleteIter(this.iter);
    }
  }

  private void push_front(Vehicle x) {
    CityFlowPINVOKE.VehicleList_push_front(swigCPtr, Vehicle.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private void push_back(Vehicle x) {
    CityFlowPINVOKE.VehicleList_push_back(swigCPtr, Vehicle.getCPtr(x));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveFirst() {
    CityFlowPINVOKE.VehicleList_RemoveFirst(swigCPtr);
  }

  public void RemoveLast() {
    CityFlowPINVOKE.VehicleList_RemoveLast(swigCPtr);
  }

  private uint size() {
    uint ret = CityFlowPINVOKE.VehicleList_size(swigCPtr);
    return ret;
  }

  public void Clear() {
    CityFlowPINVOKE.VehicleList_Clear(swigCPtr);
  }

  private Vehicle getItem(global::System.IntPtr iter) {
    Vehicle ret = new Vehicle(CityFlowPINVOKE.VehicleList_getItem(swigCPtr, iter), false);
    return ret;
  }

  private void setItem(global::System.IntPtr iter, Vehicle val) {
    CityFlowPINVOKE.VehicleList_setItem(swigCPtr, iter, Vehicle.getCPtr(val));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  private global::System.IntPtr getFirstIter() {
    global::System.IntPtr ret = CityFlowPINVOKE.VehicleList_getFirstIter(swigCPtr);
    return ret;
  }

  private global::System.IntPtr getLastIter() {
    global::System.IntPtr ret = CityFlowPINVOKE.VehicleList_getLastIter(swigCPtr);
    return ret;
  }

  private global::System.IntPtr getNextIter(global::System.IntPtr iter) {
    global::System.IntPtr ret = CityFlowPINVOKE.VehicleList_getNextIter(swigCPtr, iter);
    return ret;
  }

  private global::System.IntPtr getPrevIter(global::System.IntPtr iter) {
    global::System.IntPtr ret = CityFlowPINVOKE.VehicleList_getPrevIter(swigCPtr, iter);
    return ret;
  }

  public global::System.IntPtr insertNode(global::System.IntPtr iter, Vehicle value) {
    global::System.IntPtr ret = CityFlowPINVOKE.VehicleList_insertNode(swigCPtr, iter, Vehicle.getCPtr(value));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void eraseIter(global::System.IntPtr iter) {
    CityFlowPINVOKE.VehicleList_eraseIter(swigCPtr, iter);
  }

  private void deleteIter(global::System.IntPtr iter) {
    CityFlowPINVOKE.VehicleList_deleteIter(swigCPtr, iter);
  }

  public bool equals(global::System.IntPtr iter1, global::System.IntPtr iter2) {
    bool ret = CityFlowPINVOKE.VehicleList_equals(swigCPtr, iter1, iter2);
    return ret;
  }

  public VehicleList() : this(CityFlowPINVOKE.new_VehicleList(), true) {
  }

}

}
